//  reviews
//

const inventory = [
  {
    id: 1,
    name: "Marvel Spider-Man Mystery",
    price: 6,
    age: "0-18 months",
    category: "action figures",
    image: "../images/p1.jpeg",
    "top-picks": true,
  },
  {
    id: 2,
    name: "Marvel Spidey Sand Friends",
    price: 10,
    age: "18-36 months",
    category: "action figures",
    image: "../images/p2.jpeg",
    "top-picks": false,
  },
  {
    id: 3,
    name: "Transformers Generations",
    price: 8,
    age: "18-36 months",
    category: "action figures",
    image: "../images/p3.jpeg",
    "top-picks": true,
  },
  {
    id: 4,
    name: "Hot Wheels 5 Cars Pack (Styles Vary)",
    price: 12,
    age: "0-18 months",
    category: "cars & trucks",
    image: "../images/p4.jpeg",
    "top-picks": true,
  },
  {
    id: 5,
    name: "Hot Wheels Ultimate Garage",
    price: 12,
    age: "3-5 years",
    category: "cars & trucks",
    image: "../images/p5.jpeg",
    "top-picks": false,
  },
  {
    id: 6,
    name: "CoComelon Giant Alphabet Puzzle",
    price: 6,
    age: "3-5 years",
    category: "puzzles",
    image: "../images/p6.jpeg",
    "top-picks": true,
  },
  {
    id: 7,
    name: "Ravensburger Disney & Pixar Colour",
    price: 15,
    age: "5-7 years",
    category: "puzzles",
    image: "../images/p7.jpeg",
    "top-picks": true,
  },
  {
    id: 8,
    name: "Paw Patrol Wooden Puzzle 3 Pack",
    price: 8,
    age: "5-7 years",
    category: "puzzles",
    image: "../images/p8.jpeg",
    "top-picks": true,
  },
  {
    id: 9,
    name: "Hot Wheels City Super Twist Tyre",
    price: 11,
    age: "7-9 years",
    category: "cars & trucks",
    image: "../images/p9.jpeg",
    "top-picks": true,
  },
  {
    id: 10,
    name: "Pitter Patter Pets Dinosaur",
    price: 5,
    age: "7-9 years",
    category: "dinosaur toys",
    image: "../images/p10.jpeg",
    "top-picks": false,
  },
  {
    id: 11,
    name: "Jurassic World Dinosaur Egg Set",
    price: 6,
    age: "7-9 years",
    category: "dinosaur toys",
    image: "../images/p11.jpeg",
    "top-picks": true,
  },
  {
    id: 12,
    name: "FurReal Snackin Pet Dinosaur",
    price: 40,
    age: "5-7 years",
    category: "dinosaur toys",
    image: "../images/p12.jpeg",
    "top-picks": true,
  },
  {
    id: 13,
    name: "Ready Steady Dough",
    price: 50,
    age: "5-7 years",
    category: "puzzles",
    image: "../images/p13.jpeg",
    "top-picks": false,
  },
  {
    id: 14,
    name: "Shop Akedo",
    price: 100,
    age: "7-9 years",
    category: "cars & trucks",
    image: "../images/p14.jpeg",
    "top-picks": false,
  },
];

export const users = [
  {
    id: 1,
    email: "user1@m.com",
    password: "pass",
  },
  {
    id: 2,
    email: "user2@m.com",
    password: "pass",
  },
];

export default inventory;
